repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--check]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --project backend mypy --config-file backend/pyproject.toml backend/pynance
        language: system
        pass_filenames: false
