"""add assets transfers and asset_id

Revision ID: 0b2639f80016
Revises: b9cabe167c35
Create Date: 2026-08-12 10:36:01.358029

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2639f80016'
down_revision: str | Sequence[str] | None = 'b9cabe167c35'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('LIQUID', 'SAVINGS', 'ETF', name='assettype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=False),
    sa.Column('destination_asset_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_asset_id <> destination_asset_id', name='source_ne_destination'),
    sa.ForeignKeyConstraint(['destination_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('asset_id', sa.Integer(), nullable=False))
    op.create_foreign_key('transactions_asset_id_fkey', 'transactions', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_asset_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'asset_id')
    op.drop_table('transfers')
    op.drop_table('assets')
    # ### end Alembic commands ###
