"""add recurring_templates table

Revision ID: b9cabe167c35
Revises: 2b1849957535
Create Date: 2026-08-11 12:31:35.587902

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cabe167c35'
down_revision: str | Sequence[str] | None = '2b1849957535'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('YEARLY', 'MONTHLY', 'WEEKLY', 'CUSTOM', name='frequency'), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('next_occurrence', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_templates')
    # ### end Alembic commands ###
