"""add opening_balance to assets

Revision ID: c0868db1c4b8
Revises: 0b2639f80016
Create Date: 2026-08-12 10:56:21.059664

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0868db1c4b8'
down_revision: str | Sequence[str] | None = '0b2639f80016'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'opening_balance')
    # ### end Alembic commands ###
